import PageTemplate from "@/components/PageTemplate";
import KeyConceptSection from "@/components/KeyConceptSection";
import AlertBox from "@/components/AlertBox";
import GitHubPR from "@/components/GitHubPR";
import CodeBlock from "@/components/CodeBlock";
import CollapsibleSection from "@/components/CollapsibleSection";
import DocumentationButton from "@/components/DocumentationButton";

export default function PathPlanner() {
  return (
    <PageTemplate
      title="Adding PathPlanner"
      previousPage={{
        href: "/swerve-drive-project",
        title: "Creating a Swerve Drive Project",
      }}
      nextPage={{ href: "/logging-options", title: "Logging Options" }}
    >
      {/* Introduction */}
      <KeyConceptSection
        title="PathPlanner for Autonomous Navigation"
        description="PathPlanner is a motion profile generator for FRC robots, providing a GUI for creating complex autonomous paths and seamlessly integrating with your swerve drivetrain. The CTRE swerve generator automatically configures PathPlanner integration, making autonomous development straightforward."
        concept="PathPlanner enables visual path creation with constraints, events, and holonomic control for swerve drivetrains."
      />

      <AlertBox variant="info" title="PathPlanner Already Integrated">
        <p className="mb-2">
          Good news! The swerve drivetrain generated by Phoenix Tuner X already
          includes PathPlanner integration. The Workshop-Code repository
          demonstrates this integration in Pull Request #7, which shows the
          complete swerve and PathPlanner setup.
        </p>
      </AlertBox>

      {/* Section 1: PathPlanner Basics */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          What is PathPlanner?
        </h2>

        <p className="text-slate-600 dark:text-slate-300">
          PathPlanner is a motion planning tool specifically designed for FRC
          robots. It provides a graphical interface for creating autonomous
          paths with velocity constraints, rotation control, and event markers.
        </p>

        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-primary-50 dark:bg-primary-950/30 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Key Features
            </h3>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                <strong>Visual Path Editor:</strong> Drag-and-drop waypoints on
                a field image
              </li>
              <li>
                <strong>Holonomic Support:</strong> Independent control of
                translation and rotation
              </li>
              <li>
                <strong>Constraints:</strong> Velocity, acceleration, and
                angular velocity limits
              </li>
              <li>
                <strong>Event Markers:</strong> Trigger commands at specific
                points along the path
              </li>
              <li>
                <strong>Named Commands:</strong> Reusable command definitions
                for autonomous
              </li>
              <li>
                <strong>Auto Builder:</strong> Compose complex autos from
                multiple paths
              </li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Why PathPlanner?
            </h3>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                <strong>FRC-Specific:</strong> Built for WPILib and FRC field
                layouts
              </li>
              <li>
                <strong>Time-Saving:</strong> Visual editor is faster than
                manual tuning
              </li>
              <li>
                <strong>Repeatable:</strong> Paths saved as JSON files in your
                repo
              </li>
              <li>
                <strong>Team Friendly:</strong> Non-programmers can help create
                paths
              </li>
              <li>
                <strong>Proven:</strong> Used by top FRC teams in competition
              </li>
              <li>
                <strong>Active Development:</strong> Regular updates and FRC
                community support
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* Section 2: Installation */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Installing PathPlanner
        </h2>

        <div className="space-y-6">
          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 1: Download PathPlanner GUI
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              Download the PathPlanner desktop application for your operating
              system from the official releases page:
            </p>
            <DocumentationButton
              href="https://github.com/mjansen4857/pathplanner/releases"
              title="PathPlanner Releases"
            />
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 2: Add PathPlanner Library to build.gradle
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              The CTRE swerve generator includes PathPlanner by default, but if
              you need to add it manually or update the version:
            </p>
            <CodeBlock
              language="groovy"
              filename="build.gradle"
              code={`dependencies {
    // Other dependencies...

    // PathPlanner library
    implementation 'com.pathplanner.lib:PathplannerLib:2025.2.2'
}`}
            />
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 3: Configure AutoBuilder
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              The CommandSwerveDrivetrain generated by Phoenix Tuner X
              automatically configures PathPlanner&apos;s AutoBuilder. You can
              see this in the constructor:
            </p>
            <CodeBlock
              language="java"
              code={`// From CommandSwerveDrivetrain.java constructor
public CommandSwerveDrivetrain(
    SwerveDrivetrainConstants driveTrainConstants,
    SwerveModuleConstants... modules
) {
    // ... other initialization ...

    // Configure PathPlanner AutoBuilder
    AutoBuilder.configureHolonomic(
        this::getPose,                     // Robot pose supplier
        this::resetPose,                   // Method to reset odometry
        this::getChassisSpeeds,            // ChassisSpeeds supplier
        this::setChassisSpeeds,            // Method to drive the robot
        new HolonomicPathFollowerConfig(   // Path follower config
            new PIDConstants(10, 0, 0),    // Translation PID
            new PIDConstants(7, 0, 0),     // Rotation PID
            MAX_VELOCITY_MPS,              // Max module speed
            DRIVE_BASE_RADIUS              // Drive base radius
        ),
        this                                // Reference to this subsystem
    );
}`}
            />
          </div>
        </div>
      </section>

      {/* Section 3: Creating Paths */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Creating Your First Path
        </h2>

        <div className="space-y-6">
          <div className="bg-primary-50 dark:bg-primary-950/30 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Opening Your Project in PathPlanner
            </h3>
            <ol className="space-y-3 text-slate-600 dark:text-slate-300">
              <li>
                <strong>1.</strong> Launch the PathPlanner GUI application
              </li>
              <li>
                <strong>2.</strong> Click &quot;Open Project&quot; and navigate
                to your robot project root directory
              </li>
              <li>
                <strong>3.</strong> PathPlanner will create a{" "}
                <code>src/main/deploy/pathplanner</code> directory
              </li>
              <li>
                <strong>4.</strong> Select the appropriate field image for your
                game (e.g., 2025 Reefscape)
              </li>
            </ol>
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Path Creation Workflow
            </h3>
            <div className="space-y-4 text-slate-600 dark:text-slate-300">
              <div>
                <h4 className="font-semibold mb-2">Add Waypoints:</h4>
                <p className="text-sm">
                  Click on the field to place waypoints. The first point is your
                  starting position, and subsequent points define the path.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Adjust Heading:</h4>
                <p className="text-sm">
                  For swerve drive, you can independently control the
                  robot&apos;s heading at each waypoint. Drag the rotation
                  handle to set the desired orientation.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Set Constraints:</h4>
                <p className="text-sm">
                  Define velocity and acceleration limits for different segments
                  of the path. This is useful for slowing down around tight
                  turns.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Add Event Markers:</h4>
                <p className="text-sm">
                  Place markers along the path to trigger commands (e.g., intake
                  game pieces, shoot, etc.)
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Section 4: Workshop Code Examples */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          PathPlanner in Workshop Code
        </h2>

        <p className="text-slate-600 dark:text-slate-300">
          The Workshop-Code repository demonstrates PathPlanner integration in
          PR #7, which shows the complete swerve drivetrain setup with
          PathPlanner AutoBuilder configuration and example paths.
        </p>

        <CollapsibleSection title="PR #7: Swerve and PathPlanner">
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            This PR demonstrates the complete swerve drivetrain with integrated
            PathPlanner support. The CommandSwerveDrivetrain automatically
            configures AutoBuilder for path following, and RobotContainer shows
            how to use paths in autonomous.
          </p>

          <GitHubPR
            repository="Hemlock5712/Workshop-Code"
            pullRequestNumber={7}
            title="View Full PR #7: Swerve and PathPlanner"
            description="Click to see all changes in the pull request, including RobotContainer.java with PathPlanner integration and the CommandSwerveDrivetrain subsystem."
          />
        </CollapsibleSection>
      </section>

      {/* Section 5: Using Paths in Code */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Using Paths in Your Robot Code
        </h2>

        <CollapsibleSection title="Loading and Following a Single Path">
          <CodeBlock
            language="java"
            title="RobotContainer.java - Simple Path Following"
            code={`public class RobotContainer {
    private final CommandSwerveDrivetrain drivetrain = TunerConstants.DriveTrain;

    public Command getAutonomousCommand() {
        // Load a path file created in PathPlanner GUI
        PathPlannerPath path = PathPlannerPath.fromPathFile("Example Path");

        // Follow the path with default constraints
        return AutoBuilder.followPath(path);
    }
}`}
          />
        </CollapsibleSection>

        <CollapsibleSection title="Using PathPlanner Autos">
          <div className="space-y-4">
            <p className="text-slate-600 dark:text-slate-300">
              PathPlanner autos are complete autonomous routines created in the
              GUI, composed of multiple paths and commands:
            </p>
            <CodeBlock
              language="java"
              title="Loading a PathPlanner Auto"
              code={`public Command getAutonomousCommand() {
    // Load an auto created in PathPlanner GUI
    // The auto can include multiple paths, named commands, and wait commands
    return AutoBuilder.buildAuto("4 Note Auto");
}`}
            />
          </div>
        </CollapsibleSection>

        <CollapsibleSection title="Named Commands for Event Markers">
          <div className="space-y-4">
            <p className="text-slate-600 dark:text-slate-300">
              Register named commands that can be triggered by event markers in
              your paths:
            </p>
            <CodeBlock
              language="java"
              title="Registering Named Commands"
              code={`public class RobotContainer {
    public RobotContainer() {
        configureNamedCommands();
        configureBindings();
    }

    private void configureNamedCommands() {
        // Register commands that can be used in PathPlanner event markers
        NamedCommands.registerCommand("intakeNote",
            intake.intakeCommand());

        NamedCommands.registerCommand("shootNote",
            shooter.shootCommand());

        NamedCommands.registerCommand("stopIntake",
            intake.stopCommand());
    }
}`}
            />
          </div>
        </CollapsibleSection>
      </section>

      {/* Section 6: Tips and Best Practices */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          PathPlanner Tips & Best Practices
        </h2>

        <div className="grid md:grid-cols-2 gap-6">
          <AlertBox variant="tip" title="Path Creation">
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>Start with simple paths and gradually add complexity</li>
              <li>
                Use fewer waypoints for smoother paths (let PathPlanner
                interpolate)
              </li>
              <li>Test paths in simulation before running on real robot</li>
              <li>
                Save multiple versions of paths for testing different strategies
              </li>
            </ul>
          </AlertBox>

          <AlertBox variant="warning" title="Common Pitfalls">
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                Don&apos;t set constraints too aggressively - allow margins for
                error
              </li>
              <li>Always verify starting pose matches path starting point</li>
              <li>
                Remember to commit path files to git (in{" "}
                <code>deploy/pathplanner</code>)
              </li>
              <li>
                Test event marker timing - they execute at specific path points
              </li>
            </ul>
          </AlertBox>
        </div>

        <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-6 border-l-4 border-green-500">
          <h3 className="text-xl font-semibold text-green-900 dark:text-green-300 mb-4">
            PathPlanner Integration Complete!
          </h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            You now have PathPlanner integrated with your swerve drivetrain and
            understand how to create autonomous paths. Key takeaways:
          </p>
          <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
            <li>
              PathPlanner provides visual path creation for autonomous routines
            </li>
            <li>
              CTRE swerve generator automatically configures PathPlanner
              integration
            </li>
            <li>
              Holonomic support allows independent translation and rotation
            </li>
            <li>
              Event markers enable command execution at specific path points
            </li>
            <li>Named commands create reusable actions for autonomous</li>
            <li>Workshop Code PRs demonstrate progressive implementation</li>
          </ul>
        </div>

        <DocumentationButton
          href="https://pathplanner.dev/home.html"
          title="PathPlanner Official Documentation"
        />
      </section>
    </PageTemplate>
  );
}
