import PageTemplate from "@/components/PageTemplate";
import KeyConceptSection from "@/components/KeyConceptSection";
import AlertBox from "@/components/AlertBox";
import CodeBlock from "@/components/CodeBlock";
import DocumentationButton from "@/components/DocumentationButton";
import CollapsibleSection from "@/components/CollapsibleSection";
import Quiz from "@/components/Quiz";
import GitHubPage from "@/components/GitHubPage";
import GithubPageWithPR from "@/components/GithubPageWithPR";

export default function PathPlanner() {
  return (
    <PageTemplate
      title="Adding PathPlanner"
      previousPage={{
        href: "/swerve-drive-project",
        title: "Creating a Swerve Drive Project",
      }}
      nextPage={{ href: "/logging-options", title: "Logging Options" }}
    >
      {/* Introduction */}
      <KeyConceptSection
        title="PathPlanner for Autonomous Navigation"
        description="PathPlanner is a motion profile generator for FRC robots, providing a GUI for creating complex autonomous paths and seamlessly integrating with your swerve drivetrain. The CTRE swerve generator automatically configures PathPlanner integration, making autonomous development straightforward."
        concept="PathPlanner enables visual path creation with constraints, events, and holonomic control for swerve drivetrains."
      />

      <AlertBox variant="info" title="PathPlanner Integration">
        <p className="mb-2">
          The swerve drivetrain generated by Phoenix Tuner X doesn&apos;t
          include the PathPlanner integration by default. The Workshop-Code
          repository includes this integration in Pull Request #7, which shows
          the complete swerve and PathPlanner setup.
        </p>
      </AlertBox>

      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Workshop Code Implementation
        </h2>

        <p className="text-slate-600 dark:text-slate-300">
          This is a simplified version of the swerve drivetrain subsystem that
          only includes the necessary methods for driving the robot. We based it
          off of the{" "}
          <a
            className="text-primary-600 underline hover:no-underline hover:text-primary-800 dark:text-primary-400 dark:hover:text-primary-300 font-medium"
            href="https://github.com/CrossTheRoadElec/Phoenix6-Examples/tree/main/java/SwerveWithPathPlanner"
          >
            SwerveWithPathPlanner
          </a>{" "}
          example project from CTRE. You should copy this code into your
          CommandSwerveDrivetrain.java file, as well as the RobotContainer.java
          file.
        </p>

        <CollapsibleSection title="📁 CommandSwerveDrivetrain.java">
          <div className="space-y-4">
            <GitHubPage
              repository="Hemlock5712/Workshop-Code"
              branch="1-Swerve"
              filePath="src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java"
            />
          </div>
        </CollapsibleSection>

        <CollapsibleSection title="🎮 RobotContainer.java">
          <div className="space-y-4">
            <GithubPageWithPR
              repository="Hemlock5712/Workshop-Code"
              branch="1-Swerve"
              filePath="src/main/java/frc/robot/RobotContainer.java"
              focusFile="src/main/java/frc/robot/RobotContainer.java"
              pullRequestNumber={7}
            />
          </div>
        </CollapsibleSection>

        <AlertBox variant="info" title="🔍 Exploring the Swerve Implementation">
          <p className="mb-3">
            The swerve code includes several key files generated by Phoenix
            Tuner X:
          </p>
          <ul className="list-disc list-inside space-y-2 text-slate-600 dark:text-slate-300">
            <li>
              <strong>CommandSwerveDrivetrain:</strong> Main drivetrain
              subsystem with control methods
            </li>
            <li>
              <strong>TunerConstants:</strong> All configuration values (CAN
              IDs, gear ratios, dimensions)
            </li>
            <li>
              <strong>RobotContainer:</strong> Drive command bindings and
              controller setup
            </li>
            <li>
              <strong>generated/ folder:</strong> Low-level module and drive
              train implementations
            </li>
          </ul>
        </AlertBox>
      </section>

      {/* Section 1: PathPlanner Basics */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          What is PathPlanner?
        </h2>

        <p className="text-slate-600 dark:text-slate-300">
          PathPlanner is a motion planning tool specifically designed for FRC
          robots. It provides a graphical interface for creating autonomous
          paths with velocity constraints, rotation control, and event markers.
        </p>

        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-primary-50 dark:bg-primary-950/30 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Key Features
            </h3>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                <strong>Visual Path Editor:</strong> Drag-and-drop waypoints on
                a field image
              </li>
              <li>
                <strong>Holonomic Support:</strong> Independent control of
                translation and rotation
              </li>
              <li>
                <strong>Constraints:</strong> Velocity, acceleration, and
                angular velocity limits
              </li>
              <li>
                <strong>Event Markers:</strong> Trigger commands at specific
                points along the path
              </li>
              <li>
                <strong>Named Commands:</strong> Reusable command definitions
                for autonomous
              </li>
              <li>
                <strong>Auto Builder:</strong> Compose complex autos from
                multiple paths
              </li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Why PathPlanner?
            </h3>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                <strong>FRC-Specific:</strong> Built for WPILib and FRC field
                layouts
              </li>
              <li>
                <strong>Time-Saving:</strong> Visual editor is faster than
                manual tuning
              </li>
              <li>
                <strong>Repeatable:</strong> Paths saved as JSON files in your
                repo
              </li>
              <li>
                <strong>Team Friendly:</strong> Non-programmers can help create
                paths
              </li>
              <li>
                <strong>Proven:</strong> Used by top FRC teams in competition
              </li>
              <li>
                <strong>Active Development:</strong> Regular updates and FRC
                community support
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* Section 2: Installation */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Installing PathPlanner
        </h2>

        <div className="space-y-6">
          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 1: Download PathPlanner GUI
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              Download the PathPlanner desktop application for your operating
              system from the official releases page:
            </p>
            <DocumentationButton
              href="https://github.com/mjansen4857/pathplanner/releases"
              title="PathPlanner Releases"
            />
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 2: Add PathPlanner as a Vendor Dependency
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              Follow the steps in the PathPlanner Getting Started Guide to add
              PathPlanner as a vendor dependency.
            </p>
            <DocumentationButton
              href="https://pathplanner.dev/pplib-getting-started.html"
              title="PathPlanner Installation Guide"
            />
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Step 3: Configure AutoBuilder
            </h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">
              The CommandSwerveDrivetrain generated by Phoenix Tuner X
              automatically configures PathPlanner&apos;s AutoBuilder. You can
              see this in the constructor:
            </p>
            <CodeBlock
              filename="CommandSwerveDrivetrain.java"
              language="java"
              code={`private void configureAutoBuilder() {
  try {
    var config = RobotConfig.fromGUISettings();
    AutoBuilder.configure(
        () -> getState().Pose, // Supplier of current robot pose
        this::resetPose, // Consumer for seeding pose against auto
        () -> getState().Speeds, // Supplier of current robot speeds
        // Consumer of ChassisSpeeds and feedforwards to drive the robot
        (speeds, feedforwards) ->
            setControl(
                m_pathApplyRobotSpeeds
                    .withSpeeds(speeds)
                    .withWheelForceFeedforwardsY(
                      feedforwards.robotRelativeForcesYNewtons())
                    .withWheelForceFeedforwardsX(
                      feedforwards.robotRelativeForcesXNewtons())),
        new PPHolonomicDriveController(
            // PID constants for translation
            new PIDConstants(10, 0, 0),
            // PID constants for rotation
            new PIDConstants(7, 0, 0)),
        config,
        // Assume the path needs to be flipped for Red vs Blue, this is normally the case
        () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
        this // Subsystem for requirements
        );
  } catch (Exception ex) {
    DriverStation.reportError(
        "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
  }
}`}
            />
          </div>
        </div>
      </section>

      {/* Section 3: Creating Paths */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          Creating Your First Path
        </h2>

        <div className="space-y-6">
          <div className="bg-primary-50 dark:bg-primary-950/30 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Opening Your Project in PathPlanner
            </h3>
            <ol className="space-y-3 text-slate-600 dark:text-slate-300 mb-4">
              <li>
                <strong>1.</strong> Launch the PathPlanner GUI application
              </li>
              <li>
                <strong>2.</strong> Click &quot;Open Project&quot; and navigate
                to your robot project root directory
              </li>
              <li>
                <strong>3.</strong> PathPlanner will create a{" "}
                <code>src/main/deploy/pathplanner</code> directory
              </li>
              <li>
                <strong>4.</strong> Update robot configuration in the
                PathPlanner settings to match your robot&apos;s physical
                parameters
              </li>
            </ol>
            <DocumentationButton
              href="https://pathplanner.dev/robot-config.html"
              title="PathPlanner Settings"
            />
          </div>

          <div className="bg-slate-50 dark:bg-slate-900 p-6 rounded-lg border border-slate-200 dark:border-slate-800">
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">
              Path Creation Workflow
            </h3>
            <div className="space-y-4 text-slate-600 dark:text-slate-300">
              <div>
                <h4 className="font-semibold mb-2">Add Waypoints:</h4>
                <p className="text-sm">
                  Click on the field to place waypoints. The first point is your
                  starting position, and subsequent points define the path.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Adjust Heading:</h4>
                <p className="text-sm">
                  For swerve drive, you can independently control the
                  robot&apos;s heading at each waypoint. Drag the rotation
                  handle to set the desired orientation.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Set Constraints:</h4>
                <p className="text-sm">
                  Define velocity and acceleration limits for different segments
                  of the path. This is useful for slowing down around tight
                  turns.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Add Event Markers:</h4>
                <p className="text-sm">
                  Place markers along the path to trigger commands (e.g., intake
                  game pieces, shoot, etc.)
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Section 4: NamedCommands */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          NamedCommands
        </h2>

        <div className="space-y-4">
          <p className="text-slate-600 dark:text-slate-300">
            Register named commands that can be triggered by event markers in
            your paths:
          </p>
          <CodeBlock
            language="java"
            title="Registered Named Commands"
            code={`public class RobotContainer {
    public RobotContainer() {
        configureNamedCommands();
        configureBindings();
    }

    private void configureNamedCommands() {
        // Register commands that can be used in PathPlanner event markers
        NamedCommands.registerCommand("intakeNote",
            intake.intakeCommand());

        NamedCommands.registerCommand("shootNote",
            shooter.shootCommand());

        NamedCommands.registerCommand("stopIntake",
            intake.stopCommand());
    }
}`}
          />
        </div>
      </section>

      {/* Section 5: Tips and Best Practices */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          PathPlanner Tips & Best Practices
        </h2>

        <div className="grid md:grid-cols-2 gap-6">
          <AlertBox variant="tip" title="Path Creation">
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>Start with simple paths and gradually add complexity</li>
              <li>
                Use fewer waypoints for smoother paths (let PathPlanner
                interpolate)
              </li>
              <li>Test paths in simulation before running on real robot</li>
              <li>
                Save multiple versions of paths for testing different strategies
              </li>
            </ul>
          </AlertBox>

          <AlertBox variant="warning" title="Common Pitfalls">
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <li>
                Don&apos;t set constraints too aggressively - allow margins for
                error
              </li>
              <li>Always verify starting pose matches path starting point</li>
              <li>
                Remember to commit path files to git (in{" "}
                <code>deploy/pathplanner</code>)
              </li>
              <li>
                Test event marker timing - they execute at specific path points
              </li>
            </ul>
          </AlertBox>
        </div>

        <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-6 border-l-4 border-green-500">
          <h3 className="text-xl font-semibold text-green-900 dark:text-green-300 mb-4">
            PathPlanner Integration Complete!
          </h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4">
            You now have PathPlanner integrated with your swerve drivetrain and
            understand how to create autonomous paths. Key takeaways:
          </p>
          <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 dark:text-slate-300">
            <li>
              PathPlanner provides visual path creation for autonomous routines
            </li>
            <li>
              CTRE swerve generator automatically configures PathPlanner
              integration
            </li>
            <li>
              Holonomic support allows independent translation and rotation
            </li>
            <li>
              Event markers enable command execution at specific path points
            </li>
            <li>Named commands create reusable actions for autonomous</li>
            <li>Workshop Code PRs demonstrate progressive implementation</li>
          </ul>
        </div>

        <DocumentationButton
          href="https://pathplanner.dev/home.html"
          title="PathPlanner Official Documentation"
        />
      </section>

      {/* Quiz Section */}
      <section className="flex flex-col gap-8">
        <Quiz
          title="Knowledge Check"
          questions={[
            {
              id: 1,
              question: "What is the primary purpose of PathPlanner in FRC?",
              options: [
                "To control robot motors directly",
                "To create visual autonomous paths with velocity constraints and event markers",
                "To tune PID controllers",
                "To monitor robot battery voltage",
              ],
              correctAnswer: 1,
              explanation:
                "PathPlanner is a motion planning tool that provides a graphical interface for creating autonomous paths with velocity constraints, rotation control, and event markers. It's specifically designed for FRC robots and integrates seamlessly with WPILib.",
            },
            {
              id: 2,
              question:
                "What advantage does PathPlanner's holonomic support provide for swerve drivetrains?",
              options: [
                "Faster maximum speed",
                "Independent control of translation and rotation",
                "Reduced power consumption",
                "Automatic motor tuning",
              ],
              correctAnswer: 1,
              explanation:
                "Holonomic support allows independent control of translation (moving in X and Y directions) and rotation. This means a swerve robot can drive in one direction while simultaneously rotating to face another direction, which is crucial for efficient autonomous routines.",
            },
            {
              id: 3,
              question:
                "How do you add PathPlanner as a dependency to your robot project?",
              options: [
                "Download it from the Microsoft Store",
                "Add it as a WPILib vendor dependency using the online JSON URL",
                "Install it through Phoenix Tuner X",
                "Copy files manually into your project",
              ],
              correctAnswer: 1,
              explanation:
                "PathPlanner is added to your robot project as a WPILib vendor dependency. You follow the installation guide to add the vendor JSON URL, which automatically downloads and configures the PathPlanner library in your project.",
            },
            {
              id: 4,
              question: "What are NamedCommands used for in PathPlanner?",
              options: [
                "Naming your autonomous routines",
                "Creating reusable commands that can be triggered by event markers along paths",
                "Labeling robot subsystems",
                "Defining motor controller names",
              ],
              correctAnswer: 1,
              explanation:
                "NamedCommands are registered commands that can be triggered by event markers placed along your autonomous paths. For example, you might register 'intakeNote' and 'shootNote' commands that execute at specific points during path following.",
            },
            {
              id: 5,
              question:
                "Where are PathPlanner path files stored in your robot project?",
              options: [
                "src/main/java/frc/robot/paths/",
                "src/main/deploy/pathplanner/",
                "build/pathplanner/",
                "C:/Users/Public/PathPlanner/",
              ],
              correctAnswer: 1,
              explanation:
                "PathPlanner stores path files in the src/main/deploy/pathplanner/ directory of your robot project. These JSON files are deployed to the roboRIO and should be committed to version control so the entire team can access them.",
            },
          ]}
        />
      </section>

      {/* What's Next Section */}
      <section className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
          What&apos;s Next?
        </h2>

        <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-6 border-l-4 border-green-500">
          <h3 className="text-xl font-semibold text-green-900 dark:text-green-300 mb-4">
            Up Next: Logging Options
          </h3>
          <p className="text-slate-600 dark:text-slate-300">
            With autonomous paths configured, you&apos;ll learn about data
            logging strategies to capture telemetry and debug your robot&apos;s
            performance.
          </p>
        </div>
      </section>
    </PageTemplate>
  );
}
